spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  database:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:_agenda;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:   
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      maximum-pool-size: 70
      minimum-idle: 8
      initialization-fail-timeout: 2000
      isolate-internal-queries: true
      validation-timeout: 3000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false    
